apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b4jty9m7e-dotnet-basic
  janus-idp.io/tekton: b4jty9m7e-dotnet-basic
  backstage.io/kubernetes-id: b4jty9m7e-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: b4jty9m7e-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
